### ISSUE TITLE
[BUG] - Vercel Build rejecting static file `website/docs/Guide/Getting-Started/Commands.mdx`

### ISSUE THREAD

**Issue by PAdventures** [PAdventures/Vortexus.js#14]
**Describe the bug**
Vercel production build can't render the static file `website/docs/Guide/Getting-Started/Commands.mdx`

Error shown in Build logs:
```
website:build:         Error: Can't render static file for pathname "/docs/Guide/Getting-Started/Commands"
website:build:             at generateStaticFile (/vercel/path0/node_modules/@docusaurus/core/lib/ssg.js:119:15)
website:build:             at runNextTicks (node:internal/process/task_queues:60:5)
website:build:             at process.processImmediate (node:internal/timers:449:9)
website:build:             at async /vercel/path0/node_modules/@docusaurus/core/node_modules/p-map/index.js:57:22 {
website:build:           [cause]: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
website:build:               at Xc (server.bundle.js:41042:77)
website:build:               at Z (server.bundle.js:41043:89)
website:build:               at Yc (server.bundle.js:41046:98)
website:build:               at $c (server.bundle.js:41045:140)
website:build:               at Z (server.bundle.js:41043:345)
website:build:               at Yc (server.bundle.js:41046:98)
website:build:               at Xc (server.bundle.js:41038:145)
website:build:               at Z (server.bundle.js:41043:89)
website:build:               at Xc (server.bundle.js:41040:509)
website:build:               at Z (server.bundle.js:41043:89)
website:build:         }
```

**Comment by PAdventures** [comment]
It seems Vercel is dealing with [an issue](https://www.vercel-status.com) that may of been causing this error

**Comment by PAdventures** [comment]
The issue has been identified, fixes are being attempted

**Comment by PAdventures** [comment]
The identified issue is with the `@skyra/discord-components-react` package. A fix will be attempted. If this fails the build will run without the package until `v4` is no longer in beta

**Comment by PAdventures** [comment]
Issue resolved.
